/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIPackage;

import ClassPackage.User;
import javax.swing.JOptionPane;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author adsan
 */
public class AdminFrame extends javax.swing.JFrame {

        User adminUser;

        /**
         * Creates new form AdminFrame
         */
        private AdminFrame() {
                initComponents();
        }

        public AdminFrame(User user) {
                this.adminUser = user;
                initComponents();
                setAdminFrameProperties();
        }

        private void setAdminFrameProperties() {
                userNameLabel.setText(adminUser.getFirstName());
                userTypeLabel.setText("(" + adminUser.getDesignation() + ")");
        }

        private void setCreateNewAccountPanelProperties() {
                checkDepartmentAvailability();

        }

        private void toggleCreateNewAccountPanelVisibility() {
                boolean isVisible = createNewAccountPanel.isVisible();

                createNewAccountPanel.setVisible(!isVisible);

                if (!isVisible) {
                        setCreateNewAccountPanelProperties();
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jMenuBar1 = new javax.swing.JMenuBar();
                jMenu1 = new javax.swing.JMenu();
                jMenu2 = new javax.swing.JMenu();
                jSplitPane1 = new javax.swing.JSplitPane();
                sideBar = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                createNewAccountPanelShowBtn = new javax.swing.JButton();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                userTypeLabel = new javax.swing.JLabel();
                userNameLabel = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jPanel5 = new javax.swing.JPanel();
                logoutBtn = new javax.swing.JButton();
                body = new javax.swing.JPanel();
                createNewAccountPanel = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                userTypeFieldContainer = new javax.swing.JPanel();
                userTypeField = new javax.swing.JComboBox<>();
                jLabel4 = new javax.swing.JLabel();
                nameFieldsContainer = new javax.swing.JPanel();
                jPanel7 = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                firstNameField = new javax.swing.JTextField();
                jPanel8 = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                lastNameField = new javax.swing.JTextField();
                epfNumberFieldContainer = new javax.swing.JPanel();
                jPanel10 = new javax.swing.JPanel();
                jLabel7 = new javax.swing.JLabel();
                epfNumberField = new javax.swing.JTextField();
                departmentFieldContainer = new javax.swing.JPanel();
                departmentTypeField = new javax.swing.JComboBox<>();
                jLabel8 = new javax.swing.JLabel();
                designationFieldContainer = new javax.swing.JPanel();
                designationTypeField = new javax.swing.JComboBox<>();
                jLabel9 = new javax.swing.JLabel();
                createAccountBtnContainer = new javax.swing.JPanel();
                createAccountBtn = new javax.swing.JButton();

                jMenu1.setText("File");
                jMenuBar1.add(jMenu1);

                jMenu2.setText("Edit");
                jMenuBar1.add(jMenu2);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Admin Profile");

                jSplitPane1.setDividerSize(1);

                sideBar.setMinimumSize(new java.awt.Dimension(220, 0));
                sideBar.setPreferredSize(new java.awt.Dimension(220, 499));

                jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

                createNewAccountPanelShowBtn.setText("Create new Accounts");
                createNewAccountPanelShowBtn.setAlignmentX(0.5F);
                createNewAccountPanelShowBtn.setMaximumSize(new java.awt.Dimension(200, 40));
                createNewAccountPanelShowBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                createNewAccountPanelShowBtnActionPerformed(evt);
                        }
                });
                jPanel4.add(createNewAccountPanelShowBtn);

                jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel1.setText("Welcome,");

                userTypeLabel.setText("(Administrator)");

                userNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                userNameLabel.setText("Sandakan");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(userNameLabel)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(userTypeLabel))
                                                                                .addComponent(jLabel1))
                                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(userNameLabel)
                                                                                .addComponent(userTypeLabel))
                                                                .addContainerGap()));

                jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

                logoutBtn.setText("Log out");
                logoutBtn.setAlignmentX(0.5F);
                logoutBtn.setMaximumSize(new java.awt.Dimension(200, 40));
                logoutBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                logoutBtnActionPerformed(evt);
                        }
                });
                jPanel5.add(logoutBtn);

                javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
                sideBar.setLayout(sideBarLayout);
                sideBarLayout.setHorizontalGroup(
                                sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(sideBarLayout.createSequentialGroup()
                                                                .addGap(70, 70, 70)
                                                                .addComponent(jLabel3)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(sideBarLayout.createSequentialGroup()
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                .addGroup(sideBarLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel5,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));
                sideBarLayout.setVerticalGroup(
                                sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(sideBarLayout.createSequentialGroup()
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel3)
                                                                .addGap(46, 46, 46)
                                                                .addComponent(jPanel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                80,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                313, Short.MAX_VALUE)
                                                                .addComponent(jPanel5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                42,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));

                jSplitPane1.setLeftComponent(sideBar);

                body.setBackground(new java.awt.Color(255, 255, 255));

                createNewAccountPanel.setBackground(new java.awt.Color(255, 255, 255));
                createNewAccountPanel.setFocusable(false);

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel2.setText("Create New Account");

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

                userTypeFieldContainer.setBackground(new java.awt.Color(255, 255, 255));

                userTypeField.setModel(
                                new javax.swing.DefaultComboBoxModel<>(new String[] { "HR_MANAGER", "EMPLOYEE" }));
                userTypeField.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                userTypeFieldItemStateChanged(evt);
                        }
                });
                userTypeField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                userTypeFieldActionPerformed(evt);
                        }
                });

                jLabel4.setLabelFor(userTypeField);
                jLabel4.setText("User Type");

                javax.swing.GroupLayout userTypeFieldContainerLayout = new javax.swing.GroupLayout(
                                userTypeFieldContainer);
                userTypeFieldContainer.setLayout(userTypeFieldContainerLayout);
                userTypeFieldContainerLayout.setHorizontalGroup(
                                userTypeFieldContainerLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(userTypeFieldContainerLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(userTypeFieldContainerLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(userTypeField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                250,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(452, Short.MAX_VALUE)));
                userTypeFieldContainerLayout.setVerticalGroup(
                                userTypeFieldContainerLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(userTypeFieldContainerLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(userTypeField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                40,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));

                jPanel1.add(userTypeFieldContainer);

                nameFieldsContainer.setBackground(new java.awt.Color(255, 255, 255));

                jPanel7.setBackground(new java.awt.Color(255, 255, 255));
                jPanel7.setAlignmentX(1.0F);
                jPanel7.setAlignmentY(1.0F);

                jLabel5.setLabelFor(firstNameField);
                jLabel5.setText("First Name");

                firstNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));
                firstNameField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                firstNameFieldActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addGap(0, 0, 0)
                                                                .addGroup(jPanel7Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(firstNameField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                249,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 0, 0)));
                jPanel7Layout.setVerticalGroup(
                                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(firstNameField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                40,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)));

                jPanel8.setBackground(new java.awt.Color(255, 255, 255));

                jLabel6.setLabelFor(lastNameField);
                jLabel6.setText("Last Name");

                lastNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));
                lastNameField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                lastNameFieldActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                jPanel8.setLayout(jPanel8Layout);
                jPanel8Layout.setHorizontalGroup(
                                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel8Layout.createSequentialGroup()
                                                                .addGap(0, 0, 0)
                                                                .addGroup(jPanel8Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(lastNameField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                249,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 0, 0)));
                jPanel8Layout.setVerticalGroup(
                                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel8Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel6)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lastNameField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                40,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)));

                javax.swing.GroupLayout nameFieldsContainerLayout = new javax.swing.GroupLayout(nameFieldsContainer);
                nameFieldsContainer.setLayout(nameFieldsContainerLayout);
                nameFieldsContainerLayout.setHorizontalGroup(
                                nameFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(nameFieldsContainerLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel7,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(40, 40, 40)
                                                                .addComponent(jPanel8,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                nameFieldsContainerLayout.setVerticalGroup(
                                nameFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(nameFieldsContainerLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(nameFieldsContainerLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jPanel8,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jPanel7,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap()));

                jPanel1.add(nameFieldsContainer);

                epfNumberFieldContainer.setBackground(new java.awt.Color(255, 255, 255));

                jPanel10.setBackground(new java.awt.Color(255, 255, 255));

                jLabel7.setLabelFor(epfNumberField);
                jLabel7.setText("EPF Number");

                epfNumberField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));
                epfNumberField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                epfNumberFieldActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
                jPanel10.setLayout(jPanel10Layout);
                jPanel10Layout.setHorizontalGroup(
                                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel10Layout.createSequentialGroup()
                                                                .addGap(0, 0, 0)
                                                                .addGroup(jPanel10Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel7)
                                                                                .addComponent(epfNumberField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                249,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 0, 0)));
                jPanel10Layout.setVerticalGroup(
                                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel10Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel7)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(epfNumberField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                40,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)));

                javax.swing.GroupLayout epfNumberFieldContainerLayout = new javax.swing.GroupLayout(
                                epfNumberFieldContainer);
                epfNumberFieldContainer.setLayout(epfNumberFieldContainerLayout);
                epfNumberFieldContainerLayout.setHorizontalGroup(
                                epfNumberFieldContainerLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(epfNumberFieldContainerLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel10,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(453, Short.MAX_VALUE)));
                epfNumberFieldContainerLayout.setVerticalGroup(
                                epfNumberFieldContainerLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(epfNumberFieldContainerLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel10,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));

                jPanel1.add(epfNumberFieldContainer);

                departmentFieldContainer.setBackground(new java.awt.Color(255, 255, 255));

                departmentTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SALES", "HR" }));

                jLabel8.setLabelFor(departmentTypeField);
                jLabel8.setText("Department");

                javax.swing.GroupLayout departmentFieldContainerLayout = new javax.swing.GroupLayout(
                                departmentFieldContainer);
                departmentFieldContainer.setLayout(departmentFieldContainerLayout);
                departmentFieldContainerLayout.setHorizontalGroup(
                                departmentFieldContainerLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(departmentFieldContainerLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(departmentFieldContainerLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel8)
                                                                                .addComponent(departmentTypeField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                249,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(453, Short.MAX_VALUE)));
                departmentFieldContainerLayout.setVerticalGroup(
                                departmentFieldContainerLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(departmentFieldContainerLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel8)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(departmentTypeField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                40,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));

                jPanel1.add(departmentFieldContainer);

                designationFieldContainer.setBackground(new java.awt.Color(255, 255, 255));

                designationTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "TEACHER", "PROFESSOR", "CAREER_COUNSELOR", "PRINCIPAL", "COACH" }));
                designationTypeField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                designationTypeFieldActionPerformed(evt);
                        }
                });

                jLabel9.setLabelFor(userTypeField);
                jLabel9.setText("Designation");

                javax.swing.GroupLayout designationFieldContainerLayout = new javax.swing.GroupLayout(
                                designationFieldContainer);
                designationFieldContainer.setLayout(designationFieldContainerLayout);
                designationFieldContainerLayout.setHorizontalGroup(
                                designationFieldContainerLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(designationFieldContainerLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(designationFieldContainerLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel9)
                                                                                .addComponent(designationTypeField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                249,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(453, Short.MAX_VALUE)));
                designationFieldContainerLayout.setVerticalGroup(
                                designationFieldContainerLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(designationFieldContainerLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel9)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(designationTypeField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                40,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));

                jPanel1.add(designationFieldContainer);

                createAccountBtnContainer.setBackground(new java.awt.Color(255, 255, 255));

                createAccountBtn.setText("Create New Account");
                createAccountBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                createAccountBtnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout createAccountBtnContainerLayout = new javax.swing.GroupLayout(
                                createAccountBtnContainer);
                createAccountBtnContainer.setLayout(createAccountBtnContainerLayout);
                createAccountBtnContainerLayout.setHorizontalGroup(
                                createAccountBtnContainerLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(createAccountBtnContainerLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(createAccountBtn)
                                                                .addContainerGap(559, Short.MAX_VALUE)));
                createAccountBtnContainerLayout.setVerticalGroup(
                                createAccountBtnContainerLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(createAccountBtnContainerLayout.createSequentialGroup()
                                                                .addGap(40, 40, 40)
                                                                .addComponent(createAccountBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                50,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(18, Short.MAX_VALUE)));

                jPanel1.add(createAccountBtnContainer);

                javax.swing.GroupLayout createNewAccountPanelLayout = new javax.swing.GroupLayout(
                                createNewAccountPanel);
                createNewAccountPanel.setLayout(createNewAccountPanelLayout);
                createNewAccountPanelLayout.setHorizontalGroup(
                                createNewAccountPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(createNewAccountPanelLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(createNewAccountPanelLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(createNewAccountPanelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel2)
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(createNewAccountPanelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jPanel1,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGap(33, 33, 33)))));
                createNewAccountPanelLayout.setVerticalGroup(
                                createNewAccountPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(createNewAccountPanelLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel2)
                                                                .addGap(24, 24, 24)
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
                body.setLayout(bodyLayout);
                bodyLayout.setHorizontalGroup(
                                bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(bodyLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(createNewAccountPanel,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));
                bodyLayout.setVerticalGroup(
                                bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(bodyLayout.createSequentialGroup()
                                                                .addGap(5, 5, 5)
                                                                .addComponent(createNewAccountPanel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));

                jSplitPane1.setRightComponent(body);

                getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void createNewAccountPanelShowBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createNewAccountPanelShowBtnActionPerformed
                toggleCreateNewAccountPanelVisibility();
        }// GEN-LAST:event_createNewAccountPanelShowBtnActionPerformed

        private void createAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createAccountBtnActionPerformed
                // TODO add your handling code here:
                String userType = userTypeField.getSelectedItem().toString();
                String firstName = firstNameField.getText();
                String lastName = lastNameField.getText();
                String epfNumber = epfNumberField.getText();
                String department = departmentTypeField.getSelectedItem().toString();
                String designation = designationTypeField.getSelectedItem().toString();

                if (userType.isBlank() || firstName.isEmpty() || lastName.isEmpty() || epfNumber.isEmpty()
                                || department.isBlank() || designation.isBlank()) {
                        JOptionPane.showMessageDialog(rootPane,
                                        "Check whether all the fields are filled correctly.",
                                        "Create new account failed", JOptionPane.ERROR_MESSAGE);
                }

        }// GEN-LAST:event_createAccountBtnActionPerformed

        private void designationTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_designationTypeFieldActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_designationTypeFieldActionPerformed

        private void userTypeField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userTypeField1ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_userTypeField1ActionPerformed

        private void checkDepartmentAvailability() {
                String selectedUserType = userTypeField.getSelectedItem().toString();
                boolean isUserAnEmployee = selectedUserType.equals("EMPLOYEE");

                departmentFieldContainer.setVisible(isUserAnEmployee);
        }

        private void userTypeFieldItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_userTypeFieldItemStateChanged
                // TODO add your handling code here:
                checkDepartmentAvailability();

        }// GEN-LAST:event_userTypeFieldItemStateChanged

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
                toggleCreateNewAccountPanelVisibility();
        }// GEN-LAST:event_jButton1ActionPerformed

        private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutBtnActionPerformed
                // TODO add your handling code here:
                int option = JOptionPane.showConfirmDialog(rootPane,
                                "Are you sure you want to log out from your (Administrator) account ?",
                                "Log out confirmation",
                                JOptionPane.YES_NO_OPTION);

                if (option == 0) {
                        LoginFrame loginFrame = new LoginFrame();
                        loginFrame.setVisible(true);
                        this.dispose();
                }

        }// GEN-LAST:event_logoutBtnActionPerformed

        private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_firstNameFieldActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_firstNameFieldActionPerformed

        private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_lastNameFieldActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_lastNameFieldActionPerformed

        private void epfNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_epfNumberFieldActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_epfNumberFieldActionPerformed

        private void userTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userTypeFieldActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_userTypeFieldActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Create and display the form */
                FlatLightLaf.setup();

                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new AdminFrame().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel body;
        private javax.swing.JButton createAccountBtn;
        private javax.swing.JPanel createAccountBtnContainer;
        private javax.swing.JPanel createNewAccountPanel;
        private javax.swing.JButton createNewAccountPanelShowBtn;
        private javax.swing.JPanel departmentFieldContainer;
        private javax.swing.JComboBox<String> departmentTypeField;
        private javax.swing.JPanel designationFieldContainer;
        private javax.swing.JComboBox<String> designationTypeField;
        private javax.swing.JTextField epfNumberField;
        private javax.swing.JPanel epfNumberFieldContainer;
        private javax.swing.JTextField firstNameField;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JMenu jMenu1;
        private javax.swing.JMenu jMenu2;
        private javax.swing.JMenuBar jMenuBar1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel10;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPanel jPanel8;
        private javax.swing.JSplitPane jSplitPane1;
        private javax.swing.JTextField lastNameField;
        private javax.swing.JButton logoutBtn;
        private javax.swing.JPanel nameFieldsContainer;
        private javax.swing.JPanel sideBar;
        private javax.swing.JLabel userNameLabel;
        private javax.swing.JComboBox<String> userTypeField;
        private javax.swing.JPanel userTypeFieldContainer;
        private javax.swing.JLabel userTypeLabel;
        // End of variables declaration//GEN-END:variables
}
