/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIPackage;

import ClassPackage.Admin;
import ClassPackage.Department;
import ClassPackage.User;
import ClassPackage.DepartmentDataStorage;
import ClassPackage.Designation;
import ClassPackage.DesignationDataStorage;
import ClassPackage.UserDataStorage;

import java.util.ArrayList;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author adsan
 */
public class AdminFrame extends javax.swing.JFrame {

    UserDataStorage userDataStorage;
    DepartmentDataStorage departmentDataStorage;
    DesignationDataStorage designationDataStorage;
    Admin adminUser;

    /**
     * Creates new form AdminFrame
     */
    private AdminFrame() {
        initComponents();
    }

    public AdminFrame(Admin adminUser) {
        this.adminUser = adminUser;
        this.userDataStorage = new UserDataStorage();
        this.departmentDataStorage = new DepartmentDataStorage();
        this.designationDataStorage = new DesignationDataStorage();

        initComponents();
        setAdminFrameProperties();

        createNewAccountPanel.setVisible(false);
    }

    private void setAdminFrameProperties() {
        userNameLabel.setText(adminUser.getFirstName());
        userTypeLabel.setText("(" + adminUser.getDesignation() + ")");
    }

    private void clearAndSetCreateNewAccountPanelProperties() {
        nextUserIdLabel.setText(userDataStorage.getNextUserId());

        passwordField.setText("");
        confirmPasswordField.setText("");
        firstNameField.setText("");
        lastNameField.setText("");
        epfNumberField.setText("");

        ArrayList<Department> departments = departmentDataStorage.getData();
        DefaultComboBoxModel<String> departmentTypeFieldModel = new DefaultComboBoxModel<String>();

        for (Department department : departments) {
            departmentTypeFieldModel.addElement(department.getName());
        }

        departmentTypeField.setModel(departmentTypeFieldModel);

        ArrayList<Designation> designations = designationDataStorage.getData();
        DefaultComboBoxModel<String> designationTypeFieldModel = new DefaultComboBoxModel<String>();

        for (Designation designation : designations) {
            designationTypeFieldModel.addElement(designation.getName());
        }

        designationTypeField.setModel(designationTypeFieldModel);
    }

    private void toggleCreateNewAccountPanelVisibility() {
        boolean isVisible = createNewAccountPanel.isVisible();

        createNewAccountPanel.setVisible(!isVisible);

        if (!isVisible) {
            clearAndSetCreateNewAccountPanelProperties();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jSplitPane1 = new javax.swing.JSplitPane();
        sideBar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        createNewAccountPanelShowBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userTypeLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        body = new javax.swing.JPanel();
        createNewAccountPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        userIdLabelContainer = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        nextUserIdLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameFieldsContainer = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        passwordFieldsContainer = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        epfNumberFieldContainer = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        epfNumberField = new javax.swing.JTextField();
        designationFieldContainer = new javax.swing.JPanel();
        designationTypeField = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        departmentFieldContainer = new javax.swing.JPanel();
        departmentTypeField = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        createAccountBtnContainer = new javax.swing.JPanel();
        createAccountBtn = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Profile");
        setPreferredSize(new java.awt.Dimension(850, 666));

        jSplitPane1.setDividerSize(1);

        sideBar.setMinimumSize(new java.awt.Dimension(220, 0));
        sideBar.setPreferredSize(new java.awt.Dimension(220, 499));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        createNewAccountPanelShowBtn.setText("Create new Account");
        createNewAccountPanelShowBtn.setAlignmentX(0.5F);
        createNewAccountPanelShowBtn.setMaximumSize(new java.awt.Dimension(200, 40));
        createNewAccountPanelShowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewAccountPanelShowBtnActionPerformed(evt);
            }
        });
        jPanel4.add(createNewAccountPanelShowBtn);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Welcome,");

        userTypeLabel.setText("(Administrator)");

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        userNameLabel.setText("Sandakan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(userNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userTypeLabel))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userTypeLabel))
                .addContainerGap())
        );

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        logoutBtn.setText("Log out");
        logoutBtn.setAlignmentX(0.5F);
        logoutBtn.setMaximumSize(new java.awt.Dimension(200, 40));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel5.add(logoutBtn);

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sideBarLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 459, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(sideBar);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new java.awt.CardLayout());

        createNewAccountPanel.setBackground(new java.awt.Color(255, 255, 255));
        createNewAccountPanel.setFocusable(false);
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        createNewAccountPanel.setLayout(flowLayout1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Create New Account");
        createNewAccountPanel.add(jLabel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        userIdLabelContainer.setBackground(new java.awt.Color(255, 255, 255));
        userIdLabelContainer.setPreferredSize(new java.awt.Dimension(592, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        nextUserIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nextUserIdLabel.setText("1");

        jLabel4.setText("New User ID");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(21, 21, 21)
                .addComponent(nextUserIdLabel)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nextUserIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout userIdLabelContainerLayout = new javax.swing.GroupLayout(userIdLabelContainer);
        userIdLabelContainer.setLayout(userIdLabelContainerLayout);
        userIdLabelContainerLayout.setHorizontalGroup(
            userIdLabelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userIdLabelContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(716, Short.MAX_VALUE))
        );
        userIdLabelContainerLayout.setVerticalGroup(
            userIdLabelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userIdLabelContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(userIdLabelContainer);

        nameFieldsContainer.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setAlignmentX(1.0F);
        jPanel7.setAlignmentY(1.0F);

        jLabel5.setText("First Name");

        firstNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Last Name");

        lastNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout nameFieldsContainerLayout = new javax.swing.GroupLayout(nameFieldsContainer);
        nameFieldsContainer.setLayout(nameFieldsContainerLayout);
        nameFieldsContainerLayout.setHorizontalGroup(
            nameFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameFieldsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        nameFieldsContainerLayout.setVerticalGroup(
            nameFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameFieldsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nameFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.add(nameFieldsContainer);

        passwordFieldsContainer.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setAlignmentX(1.0F);
        jPanel9.setAlignmentY(1.0F);

        jLabel10.setText("Password");

        passwordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10)
            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Confirm Password");

        confirmPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout passwordFieldsContainerLayout = new javax.swing.GroupLayout(passwordFieldsContainer);
        passwordFieldsContainer.setLayout(passwordFieldsContainerLayout);
        passwordFieldsContainerLayout.setHorizontalGroup(
            passwordFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordFieldsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        passwordFieldsContainerLayout.setVerticalGroup(
            passwordFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordFieldsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passwordFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.add(passwordFieldsContainer);

        epfNumberFieldContainer.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("EPF Number");

        epfNumberField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(epfNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(epfNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout epfNumberFieldContainerLayout = new javax.swing.GroupLayout(epfNumberFieldContainer);
        epfNumberFieldContainer.setLayout(epfNumberFieldContainerLayout);
        epfNumberFieldContainerLayout.setHorizontalGroup(
            epfNumberFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epfNumberFieldContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(565, Short.MAX_VALUE))
        );
        epfNumberFieldContainerLayout.setVerticalGroup(
            epfNumberFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epfNumberFieldContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(epfNumberFieldContainer);

        designationFieldContainer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Designation");

        javax.swing.GroupLayout designationFieldContainerLayout = new javax.swing.GroupLayout(designationFieldContainer);
        designationFieldContainer.setLayout(designationFieldContainerLayout);
        designationFieldContainerLayout.setHorizontalGroup(
            designationFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(designationFieldContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(designationFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(designationTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(565, Short.MAX_VALUE))
        );
        designationFieldContainerLayout.setVerticalGroup(
            designationFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(designationFieldContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(designationTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(designationFieldContainer);

        departmentFieldContainer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Department");

        javax.swing.GroupLayout departmentFieldContainerLayout = new javax.swing.GroupLayout(departmentFieldContainer);
        departmentFieldContainer.setLayout(departmentFieldContainerLayout);
        departmentFieldContainerLayout.setHorizontalGroup(
            departmentFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departmentFieldContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(departmentFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(departmentTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(565, Short.MAX_VALUE))
        );
        departmentFieldContainerLayout.setVerticalGroup(
            departmentFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departmentFieldContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departmentTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(departmentFieldContainer);

        createAccountBtnContainer.setBackground(new java.awt.Color(255, 255, 255));

        createAccountBtn.setText("Create New Account");
        createAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createAccountBtnContainerLayout = new javax.swing.GroupLayout(createAccountBtnContainer);
        createAccountBtnContainer.setLayout(createAccountBtnContainerLayout);
        createAccountBtnContainerLayout.setHorizontalGroup(
            createAccountBtnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountBtnContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createAccountBtn)
                .addContainerGap(671, Short.MAX_VALUE))
        );
        createAccountBtnContainerLayout.setVerticalGroup(
            createAccountBtnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountBtnContainerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(createAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(createAccountBtnContainer);

        createNewAccountPanel.add(jPanel3);

        body.add(createNewAccountPanel, "card2");

        jSplitPane1.setRightComponent(body);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createAccountBtnActionPerformed
        String userId = nextUserIdLabel.getText();
        String password = passwordField.getText();
        String confirmPassword = confirmPasswordField.getText();
        String firstName = firstNameField.getText();
        String lastName = lastNameField.getText();
        String epfNumber = epfNumberField.getText();
        String department = departmentTypeField.getSelectedItem().toString();
        String designation = designationTypeField.getSelectedItem().toString();

        if (firstName.isBlank() || lastName.isBlank() || epfNumber.isBlank()
                || department.isBlank() || designation.isBlank()) {
            JOptionPane.showMessageDialog(null,
                    "Check whether all the fields are filled correctly.",
                    "Create new account failed", JOptionPane.ERROR_MESSAGE);

        } else if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null,
                    "Password and the Confirm Password must match.",
                    "Create new account failed", JOptionPane.ERROR_MESSAGE);

        } else if (password.length() < 8) {
            JOptionPane.showMessageDialog(null,
                    "Password must be at least 8 characters.",
                    "Create new account failed", JOptionPane.ERROR_MESSAGE);

        } else if (userDataStorage.isUserAvailable(firstName, lastName, epfNumber)) {
            JOptionPane.showMessageDialog(null,
                    "An account with entered EPF number already exists.",
                    "Create new account failed", JOptionPane.ERROR_MESSAGE);
        } else {
            User user = new User(userId, password, firstName, lastName, epfNumber, department, designation);
            boolean isAddedUserSuccess = userDataStorage.addUser(user);

            if (isAddedUserSuccess) {
                String createdUserData = "\nUser ID : " + userId + "\nEPF Number : " + epfNumber
                        + "\nFirst Name : " + firstName + "\nLast Name : " + lastName
                        + "\nDepartment : " + department + "\nDesignation : " + designation;

                JOptionPane.showMessageDialog(null,
                        "Account created successfully.\n" + createdUserData,
                        "Account created successfully.", JOptionPane.INFORMATION_MESSAGE);

                clearAndSetCreateNewAccountPanelProperties();
            }
        }
    }// GEN-LAST:event_createAccountBtnActionPerformed

    private void createNewAccountPanelShowBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createNewAccountPanelShowBtnActionPerformed
        toggleCreateNewAccountPanelVisibility();
    }// GEN-LAST:event_createNewAccountPanelShowBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(rootPane,
                "Are you sure you want to log out from your (Administrator) account ?",
                "Log out confirmation",
                JOptionPane.YES_NO_OPTION);

        if (option == 0) {
            LoginFrame loginFrame = new LoginFrame();
            loginFrame.setVisible(true);
            this.dispose();
        }

    }// GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        FlatLightLaf.setup();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JButton createAccountBtn;
    private javax.swing.JPanel createAccountBtnContainer;
    private javax.swing.JPanel createNewAccountPanel;
    private javax.swing.JButton createNewAccountPanelShowBtn;
    private javax.swing.JPanel departmentFieldContainer;
    private javax.swing.JComboBox<String> departmentTypeField;
    private javax.swing.JPanel designationFieldContainer;
    private javax.swing.JComboBox<String> designationTypeField;
    private javax.swing.JTextField epfNumberField;
    private javax.swing.JPanel epfNumberFieldContainer;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel nameFieldsContainer;
    private javax.swing.JLabel nextUserIdLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPanel passwordFieldsContainer;
    private javax.swing.JPanel sideBar;
    private javax.swing.JPanel userIdLabelContainer;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel userTypeLabel;
    // End of variables declaration//GEN-END:variables
}
