/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIPackage;

import ClassPackage.DepartmentDataStorage;
import ClassPackage.Designation;

import com.formdev.flatlaf.FlatLightLaf;

import ClassPackage.User;
import ClassPackage.Department;
import ClassPackage.DesignationDataStorage;
import ClassPackage.UserDataStorage;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author adsan
 */
public class HRManagerFrame extends javax.swing.JFrame {

    DepartmentDataStorage departmentDataStorage;
    DesignationDataStorage designationDataStorage;
    UserDataStorage userDataStorage;
    User hrManager;

    /**
     * Creates new form HRManagerForm
     */
    private HRManagerFrame() {
        initComponents();
    }

    public HRManagerFrame(User hrManager) {
        this.hrManager = hrManager;
        this.departmentDataStorage = new DepartmentDataStorage();
        this.designationDataStorage = new DesignationDataStorage();
        this.userDataStorage = new UserDataStorage();
        initComponents();

        setHRManagerFrameProperties();
        clearAndSetAddNewDepartmentPanelProperties();
        clearAndSetAddNewDesignationPanelProperties();
        clearAndSetAddNewEmployeePanelProperties();
    }

    private void setHRManagerFrameProperties() {
        userNameLabel.setText(hrManager.getFirstName());
        userTypeLabel.setText("(" + hrManager.getDesignation() + ")");
    }

    private void clearAndSetAddNewEmployeePanelProperties() {
        nextUserIdLabel.setText(userDataStorage.getNextUserId());

        passwordField.setText("");
        confirmPasswordField.setText("");
        firstNameField.setText("");
        lastNameField.setText("");
        epfNumberField.setText("");

        ArrayList<Department> departments = departmentDataStorage.getData();
        DefaultComboBoxModel<String> departmentTypeFieldModel = new DefaultComboBoxModel<String>();

        for (Department department : departments) {
            departmentTypeFieldModel.addElement(department.getName());
        }

        departmentTypeField.setModel(departmentTypeFieldModel);

        ArrayList<Designation> designations = designationDataStorage.getData();
        DefaultComboBoxModel<String> designationTypeFieldModel = new DefaultComboBoxModel<String>();

        for (Designation designation : designations) {
            String designationName = designation.getName();
            if (designationName.equals("HR_MANAGER") || designationName.equals("HR_ASSISTANT")) {
                continue;
            }

            designationTypeFieldModel.addElement(designation.getName());
        }

        designationTypeField.setModel(designationTypeFieldModel);
    }

    private void clearAndSetAddNewDepartmentPanelProperties() {
        newDepartmentIdLabel.setText(departmentDataStorage.getNextDepartmentId());

        departmentNameField.setText("");
    }

    private void clearAndSetAddNewDesignationPanelProperties() {
        newDesignationIdLabel.setText(designationDataStorage.getNextDesignationId());

        designationNameField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        sideBar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userTypeLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        createNewDepartmentPanelShowBtn = new javax.swing.JButton();
        createNewDesignationPanelShowBtn = new javax.swing.JButton();
        createNewDepartmentPanelShowBtn3 = new javax.swing.JButton();
        createNewDepartmentPanelShowBtn4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        body = new javax.swing.JPanel();
        addNewDepartmentPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        newDepartmentIdLabel = new javax.swing.JLabel();
        epfNumberFieldContainer = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        departmentNameField = new javax.swing.JTextField();
        createAccountBtnContainer = new javax.swing.JPanel();
        addDepartmentBtn = new javax.swing.JButton();
        addNewDesignationPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        newDesignationId = new javax.swing.JLabel();
        newDesignationIdLabel = new javax.swing.JLabel();
        epfNumberFieldContainer1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        designationNameLabel = new javax.swing.JLabel();
        designationNameField = new javax.swing.JTextField();
        createAccountBtnContainer1 = new javax.swing.JPanel();
        addDesignationBtn = new javax.swing.JButton();
        addNewEmployeePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        userIdLabelContainer = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        nextUserIdLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameFieldsContainer = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        passwordFieldsContainer = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        epfNumberFieldContainer2 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        epfNumberField = new javax.swing.JTextField();
        designationFieldContainer = new javax.swing.JPanel();
        designationTypeField = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        departmentFieldContainer = new javax.swing.JPanel();
        departmentTypeField = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        createAccountBtnContainer2 = new javax.swing.JPanel();
        addEmployeeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HR Manager ");
        setMinimumSize(new java.awt.Dimension(0, 500));
        setPreferredSize(new java.awt.Dimension(950, 700));

        sideBar.setMinimumSize(new java.awt.Dimension(220, 0));
        sideBar.setPreferredSize(new java.awt.Dimension(220, 499));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Welcome,");

        userTypeLabel.setText("(HR_MANAGER)");

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        userNameLabel.setText("Sandakan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(userNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userTypeLabel))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userTypeLabel))
                .addContainerGap())
        );

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        createNewDepartmentPanelShowBtn.setText("Add new Department");
        createNewDepartmentPanelShowBtn.setAlignmentX(0.5F);
        createNewDepartmentPanelShowBtn.setMaximumSize(new java.awt.Dimension(200, 40));
        createNewDepartmentPanelShowBtn.setPreferredSize(new java.awt.Dimension(200, 40));
        createNewDepartmentPanelShowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewDepartmentPanelShowBtnActionPerformed(evt);
            }
        });
        jPanel4.add(createNewDepartmentPanelShowBtn);

        createNewDesignationPanelShowBtn.setText("Add new Designation");
        createNewDesignationPanelShowBtn.setAlignmentX(0.5F);
        createNewDesignationPanelShowBtn.setMaximumSize(new java.awt.Dimension(200, 40));
        createNewDesignationPanelShowBtn.setPreferredSize(new java.awt.Dimension(200, 40));
        createNewDesignationPanelShowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewDesignationPanelShowBtnActionPerformed(evt);
            }
        });
        jPanel4.add(createNewDesignationPanelShowBtn);

        createNewDepartmentPanelShowBtn3.setText("Add new Employee");
        createNewDepartmentPanelShowBtn3.setAlignmentX(0.5F);
        createNewDepartmentPanelShowBtn3.setMaximumSize(new java.awt.Dimension(200, 40));
        createNewDepartmentPanelShowBtn3.setPreferredSize(new java.awt.Dimension(200, 40));
        createNewDepartmentPanelShowBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewDepartmentPanelShowBtn3ActionPerformed(evt);
            }
        });
        jPanel4.add(createNewDepartmentPanelShowBtn3);

        createNewDepartmentPanelShowBtn4.setText("Search Employees");
        createNewDepartmentPanelShowBtn4.setAlignmentX(0.5F);
        createNewDepartmentPanelShowBtn4.setMaximumSize(new java.awt.Dimension(200, 40));
        createNewDepartmentPanelShowBtn4.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel4.add(createNewDepartmentPanelShowBtn4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        logoutBtn.setText("Log out");
        logoutBtn.setAlignmentX(0.5F);
        logoutBtn.setMaximumSize(new java.awt.Dimension(200, 40));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel5.add(logoutBtn);

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(sideBar);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new java.awt.CardLayout(10, 10));

        addNewDepartmentPanel.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        addNewDepartmentPanel.setLayout(flowLayout1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Add New Department");
        addNewDepartmentPanel.add(jLabel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 50));

        jLabel3.setText("Department ID");

        newDepartmentIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newDepartmentIdLabel.setText("001");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(newDepartmentIdLabel)
                .addGap(0, 521, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newDepartmentIdLabel))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        addNewDepartmentPanel.add(jPanel1);

        epfNumberFieldContainer.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setLabelFor(departmentNameField);
        jLabel7.setText("Department Name");

        departmentNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));
        departmentNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentNameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(departmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout epfNumberFieldContainerLayout = new javax.swing.GroupLayout(epfNumberFieldContainer);
        epfNumberFieldContainer.setLayout(epfNumberFieldContainerLayout);
        epfNumberFieldContainerLayout.setHorizontalGroup(
            epfNumberFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epfNumberFieldContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        epfNumberFieldContainerLayout.setVerticalGroup(
            epfNumberFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epfNumberFieldContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        addNewDepartmentPanel.add(epfNumberFieldContainer);

        createAccountBtnContainer.setBackground(new java.awt.Color(255, 255, 255));

        addDepartmentBtn.setText("Add New Department");
        addDepartmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDepartmentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createAccountBtnContainerLayout = new javax.swing.GroupLayout(createAccountBtnContainer);
        createAccountBtnContainer.setLayout(createAccountBtnContainerLayout);
        createAccountBtnContainerLayout.setHorizontalGroup(
            createAccountBtnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountBtnContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addDepartmentBtn)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        createAccountBtnContainerLayout.setVerticalGroup(
            createAccountBtnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountBtnContainerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(addDepartmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        addNewDepartmentPanel.add(createAccountBtnContainer);

        body.add(addNewDepartmentPanel, "addNewDesignationPanel");

        addNewDesignationPanel.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout3.setAlignOnBaseline(true);
        addNewDesignationPanel.setLayout(flowLayout3);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Add New Designation");
        addNewDesignationPanel.add(jLabel4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 50));

        newDesignationId.setText("Designation ID");

        newDesignationIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newDesignationIdLabel.setText("001");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newDesignationId)
                .addGap(18, 18, 18)
                .addComponent(newDesignationIdLabel)
                .addGap(0, 521, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newDesignationId)
                    .addComponent(newDesignationIdLabel))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        addNewDesignationPanel.add(jPanel3);

        epfNumberFieldContainer1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        designationNameLabel.setLabelFor(departmentNameField);
        designationNameLabel.setText("Designation Name");

        designationNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));
        designationNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designationNameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(designationNameLabel)
                    .addComponent(designationNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(designationNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(designationNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout epfNumberFieldContainer1Layout = new javax.swing.GroupLayout(epfNumberFieldContainer1);
        epfNumberFieldContainer1.setLayout(epfNumberFieldContainer1Layout);
        epfNumberFieldContainer1Layout.setHorizontalGroup(
            epfNumberFieldContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epfNumberFieldContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        epfNumberFieldContainer1Layout.setVerticalGroup(
            epfNumberFieldContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epfNumberFieldContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        addNewDesignationPanel.add(epfNumberFieldContainer1);

        createAccountBtnContainer1.setBackground(new java.awt.Color(255, 255, 255));

        addDesignationBtn.setText("Add New Designation");
        addDesignationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDesignationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createAccountBtnContainer1Layout = new javax.swing.GroupLayout(createAccountBtnContainer1);
        createAccountBtnContainer1.setLayout(createAccountBtnContainer1Layout);
        createAccountBtnContainer1Layout.setHorizontalGroup(
            createAccountBtnContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountBtnContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addDesignationBtn)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        createAccountBtnContainer1Layout.setVerticalGroup(
            createAccountBtnContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountBtnContainer1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(addDesignationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        addNewDesignationPanel.add(createAccountBtnContainer1);

        body.add(addNewDesignationPanel, "addNewDepartmentPanel");

        addNewEmployeePanel.setBackground(new java.awt.Color(255, 255, 255));
        addNewEmployeePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Add New Employee");
        addNewEmployeePanel.add(jLabel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        userIdLabelContainer.setBackground(new java.awt.Color(255, 255, 255));
        userIdLabelContainer.setPreferredSize(new java.awt.Dimension(592, 40));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        nextUserIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nextUserIdLabel.setText("1");

        jLabel6.setText("New User ID");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(21, 21, 21)
                .addComponent(nextUserIdLabel)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nextUserIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout userIdLabelContainerLayout = new javax.swing.GroupLayout(userIdLabelContainer);
        userIdLabelContainer.setLayout(userIdLabelContainerLayout);
        userIdLabelContainerLayout.setHorizontalGroup(
            userIdLabelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userIdLabelContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(723, Short.MAX_VALUE))
        );
        userIdLabelContainerLayout.setVerticalGroup(
            userIdLabelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userIdLabelContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.add(userIdLabelContainer);

        nameFieldsContainer.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setAlignmentX(1.0F);
        jPanel8.setAlignmentY(1.0F);

        jLabel8.setText("First Name");

        firstNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Last Name");

        lastNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout nameFieldsContainerLayout = new javax.swing.GroupLayout(nameFieldsContainer);
        nameFieldsContainer.setLayout(nameFieldsContainerLayout);
        nameFieldsContainerLayout.setHorizontalGroup(
            nameFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameFieldsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        nameFieldsContainerLayout.setVerticalGroup(
            nameFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameFieldsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nameFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.add(nameFieldsContainer);

        passwordFieldsContainer.setBackground(new java.awt.Color(255, 255, 255));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setAlignmentX(1.0F);
        jPanel12.setAlignmentY(1.0F);

        jLabel10.setText("Password");

        passwordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10)
            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Confirm Password");

        confirmPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout passwordFieldsContainerLayout = new javax.swing.GroupLayout(passwordFieldsContainer);
        passwordFieldsContainer.setLayout(passwordFieldsContainerLayout);
        passwordFieldsContainerLayout.setHorizontalGroup(
            passwordFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordFieldsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        passwordFieldsContainerLayout.setVerticalGroup(
            passwordFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordFieldsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passwordFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.add(passwordFieldsContainer);

        epfNumberFieldContainer2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("EPF Number");

        epfNumberField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(epfNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(epfNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout epfNumberFieldContainer2Layout = new javax.swing.GroupLayout(epfNumberFieldContainer2);
        epfNumberFieldContainer2.setLayout(epfNumberFieldContainer2Layout);
        epfNumberFieldContainer2Layout.setHorizontalGroup(
            epfNumberFieldContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epfNumberFieldContainer2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(572, Short.MAX_VALUE))
        );
        epfNumberFieldContainer2Layout.setVerticalGroup(
            epfNumberFieldContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epfNumberFieldContainer2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.add(epfNumberFieldContainer2);

        designationFieldContainer.setBackground(new java.awt.Color(255, 255, 255));

        designationTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designationTypeFieldActionPerformed(evt);
            }
        });

        jLabel13.setText("Designation");

        javax.swing.GroupLayout designationFieldContainerLayout = new javax.swing.GroupLayout(designationFieldContainer);
        designationFieldContainer.setLayout(designationFieldContainerLayout);
        designationFieldContainerLayout.setHorizontalGroup(
            designationFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(designationFieldContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(designationFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(designationTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(572, Short.MAX_VALUE))
        );
        designationFieldContainerLayout.setVerticalGroup(
            designationFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(designationFieldContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(designationTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.add(designationFieldContainer);

        departmentFieldContainer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setText("Department");

        javax.swing.GroupLayout departmentFieldContainerLayout = new javax.swing.GroupLayout(departmentFieldContainer);
        departmentFieldContainer.setLayout(departmentFieldContainerLayout);
        departmentFieldContainerLayout.setHorizontalGroup(
            departmentFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departmentFieldContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(departmentFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(departmentTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(572, Short.MAX_VALUE))
        );
        departmentFieldContainerLayout.setVerticalGroup(
            departmentFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departmentFieldContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departmentTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.add(departmentFieldContainer);

        createAccountBtnContainer2.setBackground(new java.awt.Color(255, 255, 255));

        addEmployeeBtn.setText("Create New Employee");
        addEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createAccountBtnContainer2Layout = new javax.swing.GroupLayout(createAccountBtnContainer2);
        createAccountBtnContainer2.setLayout(createAccountBtnContainer2Layout);
        createAccountBtnContainer2Layout.setHorizontalGroup(
            createAccountBtnContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountBtnContainer2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addEmployeeBtn)
                .addContainerGap(671, Short.MAX_VALUE))
        );
        createAccountBtnContainer2Layout.setVerticalGroup(
            createAccountBtnContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountBtnContainer2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(addEmployeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(createAccountBtnContainer2);

        addNewEmployeePanel.add(jPanel6);

        body.add(addNewEmployeePanel, "card4");

        jSplitPane1.setRightComponent(body);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void designationTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designationTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designationTypeFieldActionPerformed

    private void createNewDepartmentPanelShowBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewDepartmentPanelShowBtn3ActionPerformed
        body.removeAll();
        body.add(addNewEmployeePanel);
        body.repaint();
        body.revalidate();
        clearAndSetAddNewEmployeePanelProperties();
    }//GEN-LAST:event_createNewDepartmentPanelShowBtn3ActionPerformed

    private void addEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeBtnActionPerformed
        String userId = nextUserIdLabel.getText();
        String password = passwordField.getText();
        String confirmPassword = confirmPasswordField.getText();
        String firstName = firstNameField.getText();
        String lastName = lastNameField.getText();
        String epfNumber = epfNumberField.getText();
        String department = departmentTypeField.getSelectedItem().toString();
        String designation = designationTypeField.getSelectedItem().toString();

        if (firstName.isBlank() || lastName.isBlank() || epfNumber.isBlank()
                || department.isBlank() || designation.isBlank()) {
            JOptionPane.showMessageDialog(null,
                    "Check whether all the fields are filled correctly.",
                    "Create new employee failed", JOptionPane.ERROR_MESSAGE);

        } else if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null,
                    "Password and the Confirm Password must match.",
                    "Create new employee failed", JOptionPane.ERROR_MESSAGE);

        } else if (password.length() < 8) {
            JOptionPane.showMessageDialog(null,
                    "Password must be at least 8 characters.",
                    "Create new employee failed", JOptionPane.ERROR_MESSAGE);

        } else if (userDataStorage.isUserAvailable(firstName, lastName, epfNumber)) {
            JOptionPane.showMessageDialog(null,
                    "An account with entered EPF number already exists.",
                    "Create new employee failed", JOptionPane.ERROR_MESSAGE);
        } else {
            User user = new User(userId, password, firstName, lastName, epfNumber, department, designation);
            boolean isAddedUserSuccess = userDataStorage.addUser(user);

            if (isAddedUserSuccess) {
                String createdUserData = "\nUser ID : " + userId + "\nEPF Number : " + epfNumber
                        + "\nFirst Name : " + firstName + "\nLast Name : " + lastName
                        + "\nDepartment : " + department + "\nDesignation : " + designation;

                JOptionPane.showMessageDialog(null,
                        "Employee account created successfully.\n" + createdUserData,
                        "Employee account created successfully.", JOptionPane.INFORMATION_MESSAGE);

                clearAndSetAddNewEmployeePanelProperties();
            }
        }
    }//GEN-LAST:event_addEmployeeBtnActionPerformed

    private void designationNameFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_designationNameFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_designationNameFieldActionPerformed

    private void addDesignationBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addDesignationBtnActionPerformed
        String newDesignationId = newDesignationIdLabel.getText();
        String newDesignationName = designationNameField.getText().replaceAll(" ", "_").toUpperCase();

        if (newDesignationName.isBlank()) {
            JOptionPane.showMessageDialog(null,
                    "Check whether the designation name field is filled correctly.",
                    "Add new Designation failed", JOptionPane.ERROR_MESSAGE);
        } else if (designationDataStorage.isDesignationAvailable(newDesignationName)) {
            JOptionPane.showMessageDialog(null,
                    "A designation named \'" + newDesignationName + "\' already exists.",
                    "Add new Designation failed", JOptionPane.ERROR_MESSAGE);
        } else {
            Designation newDesignation = new Designation(newDesignationId, newDesignationName);
            boolean isAddedDesignationSuccess = designationDataStorage.addDesignation(newDesignation);

            if (isAddedDesignationSuccess) {
                String createdUserData = "\nDesignation ID : " + newDesignationId + "\nDesignation Name : "
                        + newDesignationName;

                JOptionPane.showMessageDialog(null,
                        "Added a new designation successfully.\n" + createdUserData,
                        "Added a new designation successfully.", JOptionPane.INFORMATION_MESSAGE);

                clearAndSetAddNewDesignationPanelProperties();
            }
        }
    }// GEN-LAST:event_addDesignationBtnActionPerformed

    private void addDepartmentBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createAccountBtnActionPerformed
        String newDepartmentId = newDepartmentIdLabel.getText();
        String newDepartmentName = departmentNameField.getText().toUpperCase();

        if (newDepartmentName.isBlank()) {
            JOptionPane.showMessageDialog(null,
                    "Check whether the department name field is filled correctly.",
                    "Add new Department failed", JOptionPane.ERROR_MESSAGE);
        } else if (departmentDataStorage.isDepartmentAvailable(newDepartmentName)) {
            JOptionPane.showMessageDialog(null,
                    "A department named \'" + newDepartmentName + "\' already exists.",
                    "Add new Department failed", JOptionPane.ERROR_MESSAGE);
        } else {
            Department newDepartment = new Department(newDepartmentId, newDepartmentName);
            boolean isAddedDepartmentSuccess = departmentDataStorage.addDepartment(newDepartment);

            if (isAddedDepartmentSuccess) {
                String createdUserData = "\nDepartment ID : " + newDepartmentId + "\nDepartment Name : "
                        + newDepartmentName;

                JOptionPane.showMessageDialog(null,
                        "Added a new department successfully.\n" + createdUserData,
                        "Added a new department successfully.", JOptionPane.INFORMATION_MESSAGE);

                clearAndSetAddNewDepartmentPanelProperties();
            }
        }
    }// GEN-LAST:event_createAccountBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutBtnActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane,
                "Are you sure you want to log out from your (HR_MANAGER) account ?",
                "Log out confirmation",
                JOptionPane.YES_NO_OPTION);

        if (option == 0) {
            LoginFrame loginFrame = new LoginFrame();
            loginFrame.setVisible(true);
            this.dispose();
        }
    }// GEN-LAST:event_logoutBtnActionPerformed

    private void createNewDesignationPanelShowBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createNewDesignationPanelShowBtnActionPerformed
        // TODO add your handling code here:
        body.removeAll();
        body.add(addNewDesignationPanel);
        body.repaint();
        body.revalidate();
        clearAndSetAddNewDesignationPanelProperties();
    }// GEN-LAST:event_createNewDesignationPanelShowBtnActionPerformed

    private void createNewDepartmentPanelShowBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createNewDepartmentPanelShowBtn2ActionPerformed
        // TODO add your handling code here:
        body.removeAll();
        body.add(addNewDepartmentPanel);
        body.repaint();
        body.revalidate();
        clearAndSetAddNewDepartmentPanelProperties();
    }// GEN-LAST:event_createNewDepartmentPanelShowBtn2ActionPerformed

    private void departmentNameFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_departmentNameFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_departmentNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRManagerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDepartmentBtn;
    private javax.swing.JButton addDesignationBtn;
    private javax.swing.JButton addEmployeeBtn;
    private javax.swing.JPanel addNewDepartmentPanel;
    private javax.swing.JPanel addNewDesignationPanel;
    private javax.swing.JPanel addNewEmployeePanel;
    private javax.swing.JPanel body;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JPanel createAccountBtnContainer;
    private javax.swing.JPanel createAccountBtnContainer1;
    private javax.swing.JPanel createAccountBtnContainer2;
    private javax.swing.JButton createNewDepartmentPanelShowBtn;
    private javax.swing.JButton createNewDepartmentPanelShowBtn3;
    private javax.swing.JButton createNewDepartmentPanelShowBtn4;
    private javax.swing.JButton createNewDesignationPanelShowBtn;
    private javax.swing.JPanel departmentFieldContainer;
    private javax.swing.JTextField departmentNameField;
    private javax.swing.JComboBox<String> departmentTypeField;
    private javax.swing.JPanel designationFieldContainer;
    private javax.swing.JTextField designationNameField;
    private javax.swing.JLabel designationNameLabel;
    private javax.swing.JComboBox<String> designationTypeField;
    private javax.swing.JTextField epfNumberField;
    private javax.swing.JPanel epfNumberFieldContainer;
    private javax.swing.JPanel epfNumberFieldContainer1;
    private javax.swing.JPanel epfNumberFieldContainer2;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel nameFieldsContainer;
    private javax.swing.JLabel newDepartmentIdLabel;
    private javax.swing.JLabel newDesignationId;
    private javax.swing.JLabel newDesignationIdLabel;
    private javax.swing.JLabel nextUserIdLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPanel passwordFieldsContainer;
    private javax.swing.JPanel sideBar;
    private javax.swing.JPanel userIdLabelContainer;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel userTypeLabel;
    // End of variables declaration//GEN-END:variables
}
