/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIPackage;

import ClassPackage.Admin;
import ClassPackage.AuthService;
import ClassPackage.User;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author adsan
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */

    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userIdField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Colombo Institute of Studies - Login");
        setBackground(new java.awt.Color(0, 26, 59));
        setSize(new java.awt.Dimension(1280, 720));

        formContainer.setBackground(new java.awt.Color(0, 26, 59));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/banner-logo.png"))); // NOI18N

        userIdField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 171, 108), 2, true));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setLabelFor(userIdField);
        jLabel2.setText("User ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setLabelFor(passwordField);
        jLabel3.setText("Password");

        continueButton.setBackground(new java.awt.Color(224, 171, 108));
        continueButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        passwordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 171, 108), 2, true));

        javax.swing.GroupLayout formContainerLayout = new javax.swing.GroupLayout(formContainer);
        formContainer.setLayout(formContainerLayout);
        formContainerLayout.setHorizontalGroup(
                formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formContainerLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(formContainerLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(formContainerLayout
                                                .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                        false)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2)
                                                .addComponent(continueButton,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        128,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(userIdField,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        300,
                                                        Short.MAX_VALUE)
                                                .addComponent(passwordField))
                                        .addComponent(jLabel1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                261,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(460, Short.MAX_VALUE)));
        formContainerLayout.setVerticalGroup(
                formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formContainerLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        68,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userIdField,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordField,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(continueButton,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        41,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(153, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(formContainer,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(formContainer, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_continueButtonActionPerformed
        AuthService auth = new AuthService();
        String userId = userIdField.getText();
        String password = passwordField.getText();

        if (userId.isEmpty() || password.isEmpty()) {
            // Empty userId or password
            JOptionPane.showMessageDialog(rootPane,
                    "UserId and Password cannot be empty",
                    "Login Failed", JOptionPane.ERROR_MESSAGE);
        } else {
            User user = auth.checkUserCredentials(userId, password);
            if (user == null) {
                // Incorrect credentials
                JOptionPane.showMessageDialog(rootPane,
                        "Check whether the username and password are correct.\nContact the Administrator if you don\'t have a user account.",
                        "Login Failed", JOptionPane.ERROR_MESSAGE);
            } else {
                // Login successful
                // JOptionPane.showMessageDialog(rootPane, "Login successful.", "Login",
                // JOptionPane.INFORMATION_MESSAGE);

                switch (user.getDesignation()) {
                    case "ADMIN": {
                        Admin admin = Admin.getAnAdminFromUser(user);

                        if (admin != null) {
                            AdminFrame adminFrame = new AdminFrame(admin);
                            adminFrame.setVisible(true);
                            this.dispose();
                        }
                        break;
                    }
                    case "HR_MANAGER": {
                        Admin admin = Admin.getAnAdminFromUser(user);

                        AdminFrame adminFrame = new AdminFrame(admin);
                        adminFrame.setVisible(true);
                        this.dispose();

                        break;
                    }

                    default: {
                        JOptionPane.showMessageDialog(rootPane,
                                "You need to be an ADMIN or an HR_MANAGER to use this application.",
                                "Login Failed", JOptionPane.ERROR_MESSAGE);
                    }
                        break;
                }
                if (user.getDesignation().equals("ADMIN")) {

                }
            }
        }

    }// GEN-LAST:event_continueButtonActionPerformed

    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueButton;
    private javax.swing.JPanel formContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userIdField;
    // End of variables declaration//GEN-END:variables
}
