/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIPackage.HRManager;

import ClassPackage.Designation;
import ClassPackage.DesignationDataStorage;
import javax.swing.JOptionPane;

/**
 *
 * @author adsan
 */
public class AddNewDesignationPanel extends javax.swing.JPanel {

    private DesignationDataStorage designationDataStorage;

    /**
     * Creates new form AddNewDesignationPanel
     */
    public AddNewDesignationPanel() {
        initComponents();
        this.designationDataStorage = new DesignationDataStorage();
        clearAndSetAddNewDesignationPanelProperties();
    }

    private void clearAndSetAddNewDesignationPanelProperties() {
        newDesignationIdLabel.setText(designationDataStorage.getNextDesignationId());

        designationNameField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        newDesignationId = new javax.swing.JLabel();
        newDesignationIdLabel = new javax.swing.JLabel();
        epfNumberFieldContainer1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        designationNameLabel = new javax.swing.JLabel();
        designationNameField = new javax.swing.JTextField();
        createAccountBtnContainer1 = new javax.swing.JPanel();
        addDesignationBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 122, 255));
        jLabel4.setText("Add New Designation");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 50));

        newDesignationId.setText("Designation ID");

        newDesignationIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newDesignationIdLabel.setText("001");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newDesignationId)
                .addGap(18, 18, 18)
                .addComponent(newDesignationIdLabel)
                .addGap(0, 521, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newDesignationId)
                    .addComponent(newDesignationIdLabel))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        epfNumberFieldContainer1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        designationNameLabel.setText("Designation Name");

        designationNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));
        designationNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designationNameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(designationNameLabel)
                    .addComponent(designationNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(designationNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(designationNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout epfNumberFieldContainer1Layout = new javax.swing.GroupLayout(epfNumberFieldContainer1);
        epfNumberFieldContainer1.setLayout(epfNumberFieldContainer1Layout);
        epfNumberFieldContainer1Layout.setHorizontalGroup(
            epfNumberFieldContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epfNumberFieldContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        epfNumberFieldContainer1Layout.setVerticalGroup(
            epfNumberFieldContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epfNumberFieldContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        createAccountBtnContainer1.setBackground(new java.awt.Color(255, 255, 255));

        addDesignationBtn.setBackground(new java.awt.Color(0, 122, 255));
        addDesignationBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addDesignationBtn.setForeground(new java.awt.Color(255, 255, 255));
        addDesignationBtn.setText("Add New Designation");
        addDesignationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDesignationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createAccountBtnContainer1Layout = new javax.swing.GroupLayout(createAccountBtnContainer1);
        createAccountBtnContainer1.setLayout(createAccountBtnContainer1Layout);
        createAccountBtnContainer1Layout.setHorizontalGroup(
            createAccountBtnContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountBtnContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addDesignationBtn)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        createAccountBtnContainer1Layout.setVerticalGroup(
            createAccountBtnContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountBtnContainer1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(addDesignationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(epfNumberFieldContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(createAccountBtnContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addComponent(epfNumberFieldContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addComponent(createAccountBtnContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void designationNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designationNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designationNameFieldActionPerformed

    private void addDesignationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDesignationBtnActionPerformed
        String newDesignationId = newDesignationIdLabel.getText();
        String newDesignationName = designationNameField.getText().replaceAll(" ", "_").toUpperCase();

        if (newDesignationName.isBlank()) {
            JOptionPane.showMessageDialog(null,
                    "Check whether the designation name field is filled correctly.",
                    "Add new Designation failed", JOptionPane.ERROR_MESSAGE);
        } else if (designationDataStorage.isDesignationAvailable(newDesignationName)) {
            JOptionPane.showMessageDialog(null,
                    "A designation named \'" + newDesignationName + "\' already exists.",
                    "Add new Designation failed", JOptionPane.ERROR_MESSAGE);
        } else {
            Designation newDesignation = new Designation(newDesignationId, newDesignationName);
            boolean isAddedDesignationSuccess = designationDataStorage.addDesignation(newDesignation);

            if (isAddedDesignationSuccess) {
                String createdUserData = "\nDesignation ID : " + newDesignationId + "\nDesignation Name : "
                        + newDesignationName;

                JOptionPane.showMessageDialog(null,
                        "Added a new designation successfully.\n" + createdUserData,
                        "Added a new designation successfully.", JOptionPane.INFORMATION_MESSAGE);

                clearAndSetAddNewDesignationPanelProperties();
            }
        }
    }//GEN-LAST:event_addDesignationBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDesignationBtn;
    private javax.swing.JPanel createAccountBtnContainer1;
    private javax.swing.JTextField designationNameField;
    private javax.swing.JLabel designationNameLabel;
    private javax.swing.JPanel epfNumberFieldContainer1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel newDesignationId;
    private javax.swing.JLabel newDesignationIdLabel;
    // End of variables declaration//GEN-END:variables
}
