/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIPackage.HRManager;

import ClassPackage.Department;
import ClassPackage.Designation;
import ClassPackage.DepartmentDataStorage;
import ClassPackage.DesignationDataStorage;
import ClassPackage.Employee;
import ClassPackage.EmployeeDataStorage;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author adsan
 */
public class AddNewEmployeePanel extends javax.swing.JPanel {

    final private DepartmentDataStorage departmentDataStorage;
    final private DesignationDataStorage designationDataStorage;
    final private EmployeeDataStorage employeeDataStorage;

    /**
     * Creates new form AddNewEmployeePanel
     */
    public AddNewEmployeePanel() {
        this.departmentDataStorage = new DepartmentDataStorage();
        this.designationDataStorage = new DesignationDataStorage();
        this.employeeDataStorage = new EmployeeDataStorage();
        initComponents();
        clearAndSetAddNewEmployeePanelProperties();
    }

    /**
     * Used to clear all previous data field values and set the next employee id
     */
    private void clearAndSetAddNewEmployeePanelProperties() {
        nextUserIdLabel.setText(employeeDataStorage.getNextEmployeeId());

        passwordField.setText("");
        confirmPasswordField.setText("");
        firstNameField.setText("");
        lastNameField.setText("");
        epfNumberField.setText("");

        ArrayList<Department> departments = departmentDataStorage.getData();
        DefaultComboBoxModel<String> departmentTypeFieldModel = new DefaultComboBoxModel<>();

        for (Department department : departments) {
            departmentTypeFieldModel.addElement(department.getName());
        }

        departmentTypeField.setModel(departmentTypeFieldModel);

        ArrayList<Designation> designations = designationDataStorage.getData();
        DefaultComboBoxModel<String> designationTypeFieldModel = new DefaultComboBoxModel<>();

        for (Designation designation : designations) {
            designationTypeFieldModel.addElement(designation.getName());
        }

        designationTypeField.setModel(designationTypeFieldModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        userIdLabelContainer = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        nextUserIdLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameFieldsContainer = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        passwordFieldsContainer = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        epfNumberFieldContainer2 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        epfNumberField = new javax.swing.JTextField();
        designationFieldContainer = new javax.swing.JPanel();
        designationTypeField = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        departmentFieldContainer = new javax.swing.JPanel();
        departmentTypeField = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        createAccountBtnContainer2 = new javax.swing.JPanel();
        addEmployeeBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Add New Employee");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        userIdLabelContainer.setBackground(new java.awt.Color(255, 255, 255));
        userIdLabelContainer.setPreferredSize(new java.awt.Dimension(592, 40));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        nextUserIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nextUserIdLabel.setText("1");

        jLabel6.setText("New User ID");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(21, 21, 21)
                                .addComponent(nextUserIdLabel)
                                .addContainerGap()));
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nextUserIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));

        javax.swing.GroupLayout userIdLabelContainerLayout = new javax.swing.GroupLayout(userIdLabelContainer);
        userIdLabelContainer.setLayout(userIdLabelContainerLayout);
        userIdLabelContainerLayout.setHorizontalGroup(
                userIdLabelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(userIdLabelContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(730, Short.MAX_VALUE)));
        userIdLabelContainerLayout.setVerticalGroup(
                userIdLabelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userIdLabelContainerLayout
                                .createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        jPanel6.add(userIdLabelContainer);

        nameFieldsContainer.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setAlignmentX(1.0F);
        jPanel8.setAlignmentY(1.0F);

        jLabel8.setText("First Name");

        firstNameField.setToolTipText("First name of the employee");
        firstNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 249,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)));
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Last Name");

        lastNameField.setToolTipText("Last name of the employee");
        lastNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 249,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)));
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)));

        javax.swing.GroupLayout nameFieldsContainerLayout = new javax.swing.GroupLayout(nameFieldsContainer);
        nameFieldsContainer.setLayout(nameFieldsContainerLayout);
        nameFieldsContainerLayout.setHorizontalGroup(
                nameFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(nameFieldsContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(290, Short.MAX_VALUE)));
        nameFieldsContainerLayout.setVerticalGroup(
                nameFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(nameFieldsContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(nameFieldsContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()));

        jPanel6.add(nameFieldsContainer);

        passwordFieldsContainer.setBackground(new java.awt.Color(255, 255, 255));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setAlignmentX(1.0F);
        jPanel12.setAlignmentY(1.0F);

        jLabel10.setText("Password");

        passwordField.setToolTipText("Strong password for the employee");
        passwordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 250,
                                javax.swing.GroupLayout.PREFERRED_SIZE));
        jPanel12Layout.setVerticalGroup(
                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                .addContainerGap()));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Confirm Password");

        confirmPasswordField.setToolTipText("Confirm the strong password");
        confirmPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 250,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)));
        jPanel13Layout.setVerticalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 40,
                                        Short.MAX_VALUE)));

        javax.swing.GroupLayout passwordFieldsContainerLayout = new javax.swing.GroupLayout(passwordFieldsContainer);
        passwordFieldsContainer.setLayout(passwordFieldsContainerLayout);
        passwordFieldsContainerLayout.setHorizontalGroup(
                passwordFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(passwordFieldsContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(278, Short.MAX_VALUE)));
        passwordFieldsContainerLayout.setVerticalGroup(
                passwordFieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(passwordFieldsContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(passwordFieldsContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()));

        jPanel6.add(passwordFieldsContainer);

        epfNumberFieldContainer2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("EPF Number");

        epfNumberField.setToolTipText("EPF Number for the employee account");
        epfNumberField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(epfNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 249,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)));
        jPanel14Layout.setVerticalGroup(
                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(epfNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)));

        javax.swing.GroupLayout epfNumberFieldContainer2Layout = new javax.swing.GroupLayout(epfNumberFieldContainer2);
        epfNumberFieldContainer2.setLayout(epfNumberFieldContainer2Layout);
        epfNumberFieldContainer2Layout.setHorizontalGroup(
                epfNumberFieldContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(epfNumberFieldContainer2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(579, Short.MAX_VALUE)));
        epfNumberFieldContainer2Layout.setVerticalGroup(
                epfNumberFieldContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(epfNumberFieldContainer2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        jPanel6.add(epfNumberFieldContainer2);

        designationFieldContainer.setBackground(new java.awt.Color(255, 255, 255));

        designationTypeField.setToolTipText("Designation of the employee");
        designationTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designationTypeFieldActionPerformed(evt);
            }
        });

        jLabel13.setText("Designation");

        javax.swing.GroupLayout designationFieldContainerLayout = new javax.swing.GroupLayout(
                designationFieldContainer);
        designationFieldContainer.setLayout(designationFieldContainerLayout);
        designationFieldContainerLayout.setHorizontalGroup(
                designationFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(designationFieldContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(designationFieldContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(designationTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 249,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(579, Short.MAX_VALUE)));
        designationFieldContainerLayout.setVerticalGroup(
                designationFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(designationFieldContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(designationTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        jPanel6.add(designationFieldContainer);

        departmentFieldContainer.setBackground(new java.awt.Color(255, 255, 255));

        departmentTypeField.setToolTipText("Department of the employee");

        jLabel14.setText("Department");

        javax.swing.GroupLayout departmentFieldContainerLayout = new javax.swing.GroupLayout(departmentFieldContainer);
        departmentFieldContainer.setLayout(departmentFieldContainerLayout);
        departmentFieldContainerLayout.setHorizontalGroup(
                departmentFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(departmentFieldContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(departmentFieldContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(departmentTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 249,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(579, Short.MAX_VALUE)));
        departmentFieldContainerLayout.setVerticalGroup(
                departmentFieldContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(departmentFieldContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(departmentTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        jPanel6.add(departmentFieldContainer);

        createAccountBtnContainer2.setBackground(new java.awt.Color(255, 255, 255));

        addEmployeeBtn.setBackground(new java.awt.Color(0, 122, 255));
        addEmployeeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addEmployeeBtn.setForeground(new java.awt.Color(255, 255, 255));
        addEmployeeBtn.setText("Add Employee");
        addEmployeeBtn.setToolTipText("Add New Employee");
        addEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createAccountBtnContainer2Layout = new javax.swing.GroupLayout(
                createAccountBtnContainer2);
        createAccountBtnContainer2.setLayout(createAccountBtnContainer2Layout);
        createAccountBtnContainer2Layout.setHorizontalGroup(
                createAccountBtnContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(createAccountBtnContainer2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(addEmployeeBtn)
                                .addContainerGap(715, Short.MAX_VALUE)));
        createAccountBtnContainer2Layout.setVerticalGroup(
                createAccountBtnContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(createAccountBtnContainer2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(addEmployeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel6.add(createAccountBtnContainer2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel5)
                                .addGap(5, 5, 5)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));
    }// </editor-fold>//GEN-END:initComponents

    private void designationTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_designationTypeFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_designationTypeFieldActionPerformed

    @SuppressWarnings("deprecation")
    private void addEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addEmployeeBtnActionPerformed
        String userId = nextUserIdLabel.getText();
        String password = passwordField.getText();
        String confirmPassword = confirmPasswordField.getText();
        String firstName = firstNameField.getText();
        String lastName = lastNameField.getText();
        String epfNumber = epfNumberField.getText();
        String department = departmentTypeField.getSelectedItem().toString();
        String designation = designationTypeField.getSelectedItem().toString();

        if (firstName.isBlank() || lastName.isBlank() || epfNumber.isBlank()
                || department.isBlank() || designation.isBlank()) {
            JOptionPane.showMessageDialog(null,
                    "Check whether all the fields are filled correctly.",
                    "Create new employee failed", JOptionPane.ERROR_MESSAGE);

        } else if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null,
                    "Password and the Confirm Password must match.",
                    "Create new employee failed", JOptionPane.ERROR_MESSAGE);

        } else if (password.length() < 8) {
            JOptionPane.showMessageDialog(null,
                    "Password must be at least 8 characters.",
                    "Create new employee failed", JOptionPane.ERROR_MESSAGE);

        } else if (employeeDataStorage.isEmployeeAvailable(firstName, lastName, epfNumber)) {
            JOptionPane.showMessageDialog(null,
                    "An account with entered EPF number already exists.",
                    "Create new employee failed", JOptionPane.ERROR_MESSAGE);
        } else {
            Employee employee = new Employee(userId, firstName, lastName, epfNumber, department,
                    designation);
            boolean isAddedUserSuccess = employeeDataStorage.addEmployee(employee);

            if (isAddedUserSuccess) {
                String createdUserData = "\nUser ID : " + userId + "\nEPF Number : " + epfNumber
                        + "\nFirst Name : " + firstName + "\nLast Name : " + lastName
                        + "\nDepartment : " + department + "\nDesignation : " + designation;

                JOptionPane.showMessageDialog(null,
                        "Employee account created successfully.\n" + createdUserData,
                        "Employee account created successfully.",
                        JOptionPane.INFORMATION_MESSAGE);

                clearAndSetAddNewEmployeePanelProperties();
            }
        }
    }// GEN-LAST:event_addEmployeeBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeBtn;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JPanel createAccountBtnContainer2;
    private javax.swing.JPanel departmentFieldContainer;
    private javax.swing.JComboBox<String> departmentTypeField;
    private javax.swing.JPanel designationFieldContainer;
    private javax.swing.JComboBox<String> designationTypeField;
    private javax.swing.JTextField epfNumberField;
    private javax.swing.JPanel epfNumberFieldContainer2;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JPanel nameFieldsContainer;
    private javax.swing.JLabel nextUserIdLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPanel passwordFieldsContainer;
    private javax.swing.JPanel userIdLabelContainer;
    // End of variables declaration//GEN-END:variables
}
